import Head from "next/head";
import React from "react";

interface SeoProps {
  title: string;
}

const Seo: React.FC<SeoProps> = ({ title }) => {
  return (
    <Head>
      <title>{title} | Next Movies</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Seo;
